apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohello
  labels:
    app: gohello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gohello
  template:
    metadata:
      labels:
        app: gohello
    spec:
      containers:
        - name: gohello
          image: creativeentropyaj/gohello
          ports:
          - containerPort: 8888
